[package]
name = "calloop"
version = "0.6.4"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://docs.rs/calloop/"
repository = "https://github.com/Smithay/calloop"
license = "MIT"
description = "A callback-based event loop"
keywords = [ "events", "loop", "callback", "eventloop", "unix" ]
autotests = false
edition = "2018"
readme = "README.md"

[badges]
codecov = { repository = "Smithay/calloop" }

[dependencies]
log = "0.4"
nix = "0.18"

[[test]]
name = "signals"
harness = false
